version: '3'
services:
  app:
    build: .
    image: vrochacaio/incidentezero-app
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:h2:~/zeroincidentes
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=